#!/bin/bash

# Getting started
#
# Compile spark with hadoop 2.2.0 -SPARK_HADOOP_VERSION=2.2.0 SPARK_YARN=true ./sbt/sbt clean assembly to generate spark.jar

# Compile pig with -Dhadoopversion=23 flag

# Configure following environment variables to run it on YARN cluster


# Follow this guide for for enabling running spork: 
##	http://docs.sigmoidanalytics.com/index.php/Setting_up_spork_with_spark_0.8.1

export HADOOP_CONF_DIR=/Users/mayur/Desktop/BuildSpark/hadoop-1.0.4/conf
export HADOOP_HOME=/Users/mayur/Desktop/BuildSpark/hadoop-1.0.4/

# Not necessary after SPARK-1053
#export SPARK_YARN_APP_JAR=build/pig-withouthadoop.jar 

# To debug OOMs
#export SPARK_JAVA_OPTS=" -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.dump"

# Settings to work with YARN, spark jar compiled with hadoop 2
export SPARK_MASTER=local[2]

#if want to run on spark master
#export SPARK_MASTER=spark://-------:7077
#export MESOS_NATIVE_LIBRARY= <libmesos.so>
####


# jars to ship, pig-withouthadoop.jar to workaround Classloader issue
#export SPARK_JAR=/Users/mayur/Desktop/BuildSpark/pig/build/ivy/lib/Pig/spark-core_2.9.3-0.8.1-incubating.jar

# Pig settings
export PIG_CLASSPATH=/Users/mayur/Desktop/BuildSpark/pig/pig-withouthadoop.jar:/Users/mayur/Desktop/BuildSpark/pig/lib/spark/mesos-0.9.0.jar:/Users/mayur/Desktop/BuildSpark/pig/build/ivy/lib/Pig/*:$HADOOP_CONF_DIR


# Cluster settings
export SPARK_WORKER_CORES=1
export SPARK_WORKER_MEMORY=1g
export SPARK_WORKER_INSTANCES=1

bin/pig -x spark "$@"
